spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        default_schema: analytics_views

dadata:
  auth:
    x-secret: ${DADATA_X_SECRET}
    token: ${DADATA_TOKEN}
  request:
    cleaner:
      address:
        url: ${DADATA_CLEANER_URL}
    suggestion:
      fias:
        url: ${DADATA_FIAS_URL}
        token: ${DADATA_FIAS_TOKEN}

server:
  port: ${PORT:8091}