spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

dadata:
  auth:
    x-secret: ${DADATA_X_SECRET}
    token: ${DADATA_TOKEN}
  request:
    cleaner:
      address:
        url: ${DADATA_CLEANER_URL}